### ISSUE TITLE
The tool stopped working on MacOS 15.4

### ISSUE THREAD

**Issue by legosx** [sqlc-dev/sqlc#3916]
### Version

1.28.0

### What happened?

Running the tool via:
```
go run -mod=mod github.com/sqlc-dev/sqlc/cmd/sqlc generate
```
Getting the log:

### Relevant log output

```shell
# github.com/pganalyze/pg_query_go/v5/parser
src_port_snprintf.c:374:1: error: static declaration of 'strchrnul' follows non-static declaration
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/_string.h:198:9: note: previous declaration is here
src_port_snprintf.c:438:27: warning: 'strchrnul' is only available on macOS 15.4 or newer [-Wunguarded-availability-new]
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/_string.h:198:9: note: 'strchrnul' has been marked as being introduced in macOS 15.4 here, but the deployment target is macOS 15.0.0
src_port_snprintf.c:438:27: note: enclose 'strchrnul' in a __builtin_available check to silence this warning
```

### Database schema

Any schema

### SQL queries

Any queries

### Configuration

Fails even without any config

### Playground URL

I think it's clear without it

### What operating system are you using?

MacOS 15.4

### What database engines are you using?

Postgres

### What type of code are you generating?

Go code

**Comment by hishamk** [comment]
Same error as well

**Comment by havsar** [comment]
`export CGO_CFLAGS="-DHAVE_STRCHRNUL -mmacosx-version-min=15.4"`
`export MACOSX_DEPLOYMENT_TARGET="15.4"`

This is a temporary solution that worked for me until it gets fixed.

**Comment by nginx-nickc** [comment]
sqlc from `main`, with `github.com/pganalyze/pg_query_go/v6@v6.1.0`  seems to work too.

**Comment by rubberduck203** [comment]
Not sure if this helps. I stumbled across this issue while looking for a solution to the same problem with the ruby gem `pg_query`.
https://github.com/pganalyze/pg_query/issues/327

**Comment by pgr0ss** [comment]
If I understand correctly, we need the `pg_query_go` upgrade (which is part of https://github.com/sqlc-dev/sqlc/pull/3922) and then we need a new release of `sqlc`. Any chance we can get a timeline on these changes? Thanks!

**Comment by kyleconroy** [comment]
Yep! New release was supposed to go out last week, but I'm glad I waited for pg_query_go 6.1.0 to land

**Comment by kyleconroy** [comment]
The upgrade to pg_query_go 6.1.0 has been merged. For those that can, please build from main and let me know if your issue is fixed.

**Comment by connor15mcc** [comment]
The upgraded `pg_query_go` (from main) fixes this for me. Thanks! Will wait for a release

**Comment by vladmiller** [comment]
@kyleconroy @connor15mcc I see that sqlc still requires an older pg_query_go. I guess we need to wait until newer version of sqlc is available as well? 

```
	github.com/pganalyze/pg_query_go/v5 v5.1.0 // indirect
	github.com/pganalyze/pg_query_go/v6 v6.1.0 // indirect
```

**Comment by kyleconroy** [comment]
@vladmiller good catch, I need to run `go mod tidy`. It's an indirect import, so I may need to upgrade the wasilibs dependency as well.

**Comment by WillAbides** [comment]
The current HEAD (b4f2571384bfe1128fe5f155bfa191a602997e9b) works for me on macos 15.4.

**Comment by vladmiller** [comment]
@kyleconroy yay! Latest `main` works fine. Thank you!

In [docs](https://docs.sqlc.dev/en/latest/overview/install.html), one way to install sqlc is 

```
go install github.com/sqlc-dev/sqlc/cmd/sqlc@latest
```

and latest points to the version that was released in January. I'd suggest maybe do a GH release as well or update the docs.

**Comment by matjam** [comment]
painfully, if you're stuck on 15.2 then this seems to happen;

```
 go install github.com/sqlc-dev/sqlc/cmd/sqlc@latest

# github.com/pganalyze/pg_query_go/v5/parser
src_port_snprintf.c:374:1: error: static declaration of 'strchrnul' follows non-static declaration
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/_string.h:198:9: note: previous declaration is here
src_port_snprintf.c:438:27: warning: 'strchrnul' is only available on macOS 15.4 or newer [-Wunguarded-availability-new]
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/_string.h:198:9: note: 'strchrnul' has been marked as being introduced in macOS 15.4 here, but the deployment target is macOS 15.0.0
src_port_snprintf.c:438:27: note: enclose 'strchrnul' in a __builtin_available check to silence this warning
```

I'll make sure my SDK is up to date.

**Comment by kyleconroy** [comment]
latest does do what you think it does. That’s the latest tagged release. If
you change it to main I believe it works as intended.

**Comment by macrael** [comment]
Who has the power to cut a new release? We're on v1.28.0 which is still broken and would rather update to a real release rather than main

**Comment by kyleconroy** [comment]
That's me! Been busy at work but trying to create a release in the next two days. Thanks for understanding.

**Comment by kyleconroy** [comment]
Alright, sadly the release workflow is borked right now due to some Apple code signing issues. I'm going to be traveling, so I'm not sure a release will happen in the next 10 days. I could tag a new release and not provide binaries, but that would cause more confusion. 

In the meantime, please install from `main` which fixes this issue.

```
$ go install github.com/sqlc-dev/sqlc/cmd/sqlc@main
```

**Comment by kyleconroy** [comment]
1.29.0 is out!

**Comment by macrael** [comment]
Thanks so much!
